name: zstore_flutter
description: A Zindgi Store Flutter Application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  file_picker: ^5.2.1
  fluttertoast: ^8.1.1
  toast: ^0.1.5
  flutter_html: ^3.0.0-alpha.3

  cupertino_icons: ^1.0.2

 #For tracking order
  im_stepper: ^1.0.1+1

  # For shimmer effects
  shimmer: ^2.0.0

  # local database
  sqflite: ^2.1.0

  #works to notifies the counts
  badges: ^2.0.3

  #for animated appBar
  flutter_zoom_drawer: ^3.0.3

  #for local storage
  flutter_secure_storage: ^5.0.2


  dartz: ^0.10.1

  # For image selection from gallery or storage
  image_picker: ^0.8.5+3
  #used for dynamic screen sizes
  flutter_screenutil: ^5.5.3+2

 #this is for rating Stars
  flutter_rating_bar: ^4.0.1

  # For creating simple shadow
  simple_shadow: ^0.3.0

  # For loading images from network and storing theme in cache
  cached_network_image: ^3.2.0

  #used for dependency injection as resource locator
  get_it: ^7.2.0

  #used for state management
  provider: ^6.0.3

  #used to check internet connectin
  internet_connection_checker: ^0.0.1+4

  #used to override equality
  equatable: ^2.0.3

  # Used to format dates
  intl: ^0.17.0

  #Used for Http Client
  dio: ^4.0.6

  #to show logs in different colors
  logger: any

  # For virtual different screen sizes
  device_preview: ^1.1.0

  #to add Google Fonts
  google_fonts: ^3.0.1

  # To incorporate the SVGs in Flutter
  flutter_svg: ^1.1.5

  # For OTP Pin Textfields
  pin_code_fields: ^7.4.0

  # For bottom nav bar and as a tab view on the page views
  bottom_navy_bar: ^6.0.0
  animated_bottom_navigation_bar: ^1.0.1

  # For masking input form fields like (03xx-xxxxxxx)
  mask_text_input_formatter: ^2.4.0

  # For page animations
  animations: ^2.0.3

 #for radio buttons
  radio_group_v2: ^1.0.2

  #to encrypt and decrpt data
  encrypt: any
  latlng: ^0.1.0
  geolocator: ^8.2.1
  geolocator_apple: ^2.1.3
  geolocator_android: ^3.1.8
  dotted_border: ^2.0.0+2
  google_maps_flutter: ^2.1.12
  flutter_polyline_points: ^1.0.0
  carousel_slider: ^4.1.1




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1


flutter:


  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/images/
